<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
	<div class="main-content-inner">
<div class="widget-box divBlanco">
		<div class="alert alert-info" align="center">
			<h4>Consulta De Personas Registradas En El Sistema <i class="fa fa-users fa-lg"></i></h4>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
					<div id="consulta_personas" class="col-xs-12">
							<table id="consulta_personas_tabla"></table>
							<div id="jqGridPager"></div>
					</div>
				</div>
			</div>
		</div>
		<hr>
			
			</div><!-- /.page-content -->
		</div>
		</div>
		<div id="dialog-confirm" title="Dialog Title" hidden="hidden">¿Esta seguro de Cancelar?</div>	
		<div id="prod"></div>
		<div id="resultado" align="center"></div>
		<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>

