	<div class="widget-box divBlanco">
		<div class="alert alert-info" align="center">
			<h4>Consulta de personas registradas en el sistema <i class="fa fa-users fa-lg"></i></h4>
		</div>
		<hr>
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
					<div class="col-xs-12">
						<div class="table-header">
							Personas registradas.
						</div>
						<div>
							<form action="<?php  echo BASE_URL;?>personal/listing" method="post">
								<table id="dynamic-table" class="table table-striped table-bordered table-hover">
									<thead>
										<tr>
											<th class="center">
												<label class="pos-rel">
													#
												</label>
											</th>
											<th class="center">Cedula</th>
											<th class="center">Nombres</th>
											<th class="center">Apellidos</th>
											<th class="center">Fecha de ingreso</th>
											<th class="center">Teléfono</th>
											<th class="center">Acciones</th>
										</tr>
									</thead>
									<tbody>
									<?php if(count($this->_listado) >= 1): ?>
										<?php foreach ($this->_listado as $persona): ?>
										<tr>
											<td class="center"><?php echo $persona['numeracion'];?></td>
											<td><?php echo $persona['cedula']; ?></td>
											<td><?php echo $persona['nombre']; ?>&nbsp;&nbsp;<?php echo $persona['nombre2']; ?></td>
											<td><?php echo $persona['apellido']; ?>&nbsp;&nbsp;<?php echo $persona['apellido2']; ?></td>
											<td class="center"><?php echo $persona['fecha_ingreso'];?></td>
											<td class="center"><?php echo $persona['telefono'];?></td>
											<td class="center">
												<div class="hidden-sm hidden-xs action-buttons">
													<a class="btn-app  btn-detalles  btn-sm" id="detalle_persona"
														onclick="pickOpen('prod', 'id_prod',
														'<?php echo BASE_URL."personal/update/". $persona['id_persona'] ?>',
														90, 96, 85, 1);show('prod',500);show('id_aceptar',500);hide('id_buscar',500);"
														style=cursor:pointer; >
														<i class="glyphicon glyphicon-search"></i>
														Detalles
													</a>
													<a class="btn-app  btn-imprimir  btn-sm" id="detalle_persona" target="_blank"
														href="<?php echo BASE_URL."pdf/pdfDetallePersona/". $persona['id_persona'] ?>" >
														<i class="ace-icon fa fa-print bigger fa-lg"></i>
														Imprimir
													</a>
													<a class="btn-app btn-eliminar btn-sm" href="<?php echo BASE_URL."personal/delete/". $persona['id_persona'] ?>">
														<i class="ace-icon fa fa-trash-o bigger fa-lg"></i>
														Eliminar
													</a>
												</div>
											</td>
										</tr>
										<?php endforeach ?>
										<?php else: ?>
											<tr>
												<td colspan="8" align="center">
													<div class="alert alert-danger">
														<b>
															<font size="5">
																No hay personal registrado.
															</font>
														</b>
													</div>
												</td>

											</tr>
											<?php endif; ?> 										
									</tbody>
								</table>
								<br>
								</div><!-- /.col -->
							</form>
						</div>
					</div>
				</div>
			</div>
			
			</div><!-- /.page-content -->
		</div>
		</div>
		<div id="prod"></div>
		<div id="resultado" align="center"></div>
		<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>

