<div class    ="page-content" ><!-- /.page-content -->
<form class   ="form-horizontal" role="form"  method="post"  id="registro_persona" name="registro_persona" >


	<div class="widget-box">
	<div class="widget-header widget-header-blue widget-header-flat">
	<div class    ="page-header">
	<h1>Registro del personal.</h1>
	</div>
	</div>

	<div class="widget-body">
	<div class="widget-main">
	<div id="my-wizard">
		<div>
		<ul class="steps">
		<li data-step="1" class="active">
		<span class="step">1</span>
		<span class="title">Datos personales</span>
		</li>

		<li data-step="2">
		<span class="step">2</span>
		<span class="title">Información de hijos</span>
		</li>

		<li data-step="3">
		<span class="step">3</span>
		<span class="title">Payment Info</span>
		</li>

		<li data-step="4">
		<span class="step">4</span>
		<span class="title">Other Info</span>
		</li>
		</ul>
		</div>

	<hr />

	<div class="step-content pos-rel">
	<div class="step-pane active" data-step="1" id="divPersona">										


	<div class="form-group">
	<input type="hidden" name="id" value="0">
	<label class="control-label col-xs-12 col-sm-3 no-padding-right">Nombres:</label>

	<div class="col-xs-12 col-sm-7">
	<div class="col-sm-6">
	<input type   ="text" name="nombre" id="nombre" placeholder="Primer Nombre" class="form-control" />
	</div>
	<div class="col-sm-6">
	<input type   ="text" name="nombre2" id="nombre2" placeholder="Segundo Nombre" class="form-control" />
	</div>										
	</div>
	</div>

	<div class="space-2"></div>

	<div class="form-group">
	<label class="control-label col-xs-12 col-sm-3 no-padding-right">Apellidos:</label>

	<div class="col-xs-12 col-sm-7">
	<div class="col-sm-6">
	<input type   ="text" name="apellido" id="apellido" placeholder="Primer apellido" class="form-control" />
	</div>
	<div class="col-sm-6">
	<input type   ="text" name="apellido2" id="apellido2" placeholder="Segundo apellido" class="form-control" />
	</div>										
	</div>
	</div>

	<div class="space-2"></div>
	<div class="form-group">
	<label class="control-label col-sm-3 no-padding-right" for="cedula">Cédula: </label>
	<div class="col-sm-8">
	<div class="col-sm-4">
	<div class="input-group">
	<input type   ="text" name="cedula" id="cedula" class="form-control" />
	<span class   ="input-group-addon">
	<i class      ="fa 	fa-credit-card "></i>
	</span>
	</div>
	</div>
	<div class="col-sm-8">
	<div>
	<label class="control-label col-sm-3 no-padding-right" for="sexo">Sexo:</label>
	</div>
	<div class="col-sm-2">
	<div class="clearfix">
	<div>
	<label class="line-height-1 blue">
	<input  value="16" type="radio" class="ace" name="sexos" />
	<span class="lbl"> Masculino</span>
	</label>
	</div>
	</div>
	</div>
	<div class="col-sm-2">
	<div class="clearfix">
	<div class="col-sm-12">
	<label class="line-height-1 blue">
	<input  value="17" type="radio" class="ace" name="sexos" />
	<span class="lbl"> Femenino</span>
	</label>
	</div>
	</div>
	</div>
	</div>											
	</div>										
																		
	</div>	


	<div class="hr hr-dotted"></div>	

	<div class="space-2"></div>
	<div class="form-group">
	<label class="control-label col-sm-3 no-padding-right" for="cedula">Fecha de nacimiento: </label>
	<div class="col-sm-8">
	<div class="col-sm-5">
	<div class="input-group">
	<input class  ="form-control date-picker" name="fecha_nacimiento" id="fecha_nacimiento" type="date" data-date-format="yyyy-mm-dd" />
	<span class   ="input-group-addon">
	<i class      ="fa fa-calendar bigger-110"></i>
	</span>		
	</div>
	</div>
	<div class="col-sm-6">
	<label class="control-label col-sm-3 no-padding-right" for="cedula">Telefono: </label>
	<div class="col-sm-9">
	<div class="col-sm-12">
	<div class="input-group">
	<input class  ="form-control input-mask-phone" type="text" id="telefono" name="telefono" />
	<span class   ="input-group-addon">
	<i class      ="ace-icon fa fa-phone"></i>
	</span>
	</div>
	</div>
	</div>										
	</div>										
	</div>																	
	</div>

	<div class="space-2"></div>
	<div class="form-group">
	<label class="control-label col-sm-3 no-padding-right" for="cedula">Otro telefono: </label>
	<div class="col-sm-9">
	<div class="col-sm-3">
	<div class="input-group">
	<input class  ="form-control input-mask-phone" type="text" id="otro_telefono" name="otro_telefono" />
	<span class   ="input-group-addon">
	<i class      ="ace-icon fa fa-phone"></i>
	</span>
	</div>
	</div>
	<div class="col-sm-8">
	<label class="control-label col-sm-3 no-padding-right" for="cedula">Fecha de ingreso: </label>
	<div class="col-sm-7">
	<div class="col-sm-12">
	<div class="input-group">
	<input class  ="form-control date-picker" name="fecha_ingreso" id="fecha_ingreso" type="date" data-date-format="yyyy-mm-dd" />
	<span class   ="input-group-addon">
	<i class      ="fa fa-calendar bigger-110"></i>
	</span>		
	</div>	</div>
	</div>										
	</div>										
	</div>																	
	</div>		

	<div class="space-2"></div>
	<div class="form-group">
	<label class="control-label col-sm-3 no-padding-right" for="correo">Correo personal: </label>
	<div class="col-sm-8">
	<div class="col-sm-5">
	<div class="input-group">
	<input class  ="form-control" type="text"  name="correo" />
	<span class   ="input-group-addon">
	<i class      ="fa fa-weixin"></i>
	</span>
	</div>
	</div>												
	</div>																	
	</div>

		
	<div class="form-group">
	<div class="col-sm-6">
	<div class="col-sm-6">
	</div>										
	</div>										
	</div>	
																					

	<div class="hr hr-dotted"></div>		
	<div align="center" class="col-sm-4">
	<label class="control-label col-sm-2 no-padding-right" for="estado">Estado: </label>								
	<div class    ="input-group">
	<select  id="estado" name="estado" onclick="search_municipio(this.selectedIndex)">
	<option value ="" default selected>Seleccione un estado...</option>
	<?php foreach ($this->_direccionEstado as $estado):?>
	<?php // if ($estado['estado']==$estado['estado']): ?>
	<option  value ="<?php  echo $estado['id_referencial']; ?>"><?php  echo $estado['estado']; ?></option>
	<?php //endif ?>
	<?php endforeach ?>
	</select>
	</div>									
	</div>

	<div align="center" class="col-sm-4">
	<label class="control-label col-sm-2 no-padding-right" for="municipio">Municipio: </label>											
	<div class    ="input-group">
	<select  id="municipio" name="municipio">
	<option value ="" default selected>Seleccione un municipio...</option>
	<?php foreach ($this->_direccionMunicipio as $municipio):?>
	<option value ="<?php  echo $municipio['id_referencial']; ?>"><?php  echo $municipio['municipio']; ?></option>
	<?php endforeach ?>
	</select>
	</div>								
	</div>

	<div align="center" class="col-sm-4">
	<label class="control-label col-sm-2 no-padding-right" for="parroquia">Parroquia: </label>											
	<div class    ="input-group">
	<select  id="direccion" name="direccion">
	<option value ="" default selected>Seleccione una parroquia...</option>
	<?php foreach ($this->_direccionParroquia as $parroquia):?>
	<option value ="<?php  echo $parroquia['id_referencial']; ?>"><?php  echo $parroquia['parroquia']; ?></option>
	<?php endforeach ?>
	</select>
	</div>									
	</div>											
	<br><br>
	<div class="hr hr-dotted"></div>	

	<div class="form-group">
	<label class="control-label col-sm-3 no-padding-right" for="ubicacion">Ubicación: </label>
	<div class="col-sm-9">
	<div class="col-sm-9">
	<div class="input-group">
	<input class  ="form-control" type="text"  name="ubicacion" placeholder="Zona donde vive la persona"/>
	<span class   ="input-group-addon">
	<i class      ="fa 	fa-globe "></i>
	</span>
	</div>
	</div>										
	</div>										
	</div>								


	</form>
	</div>

	<div class="step-pane" data-step="2">
	<div>

	<table align="center">
	<tr>
	<td>
	<label for="">¿Esta persona tiene hijos?</label>
	</td>
	</tr>
	<tr>
	<td>
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
	&nbsp; 

	<label class="blue">
	<input  value="16" type="radio" class="ace" name="hijos" 
	onchange="showElementos('infoHijos')" value="16" />
	<span class="lbl"> Si</span>
	</label>
	&nbsp; 
	<label class="blue">
	<input onchange="cerrarDivHijos('infoHijos')" value="16" type="radio" class="ace" name="hijos" />
	<span class="lbl"> No</span>
	</label>																														
	</td>

	</tr>
	</table>

	<hr>

	<div id="infoHijos" class="col-sm-16" hidden><!-- informacion de los hijos -->
	<h3 align="center" class="lighter block blue">Ahora podra registrar un maximo de 5 hijos</h3>
	<br>

	<div class="form-group">
	<input type="hidden" name="id" value="0">
	<input type="hidden" name="cedula" value="-">
	<input type="hidden" name="fecha_nacimiento" value="2016-01-01">
	<input type="hidden" name="fecha_ingreso" value="2016-01-01">
	<input type="hidden" name="telefono" value="-">
	<input type="hidden" name="otro_telefono" value="-">
	<input type="hidden" name="correo" value="-">
	<input type="hidden" name="correo_institucional" value="-">
	<input type="hidden" name="direccion" value="0">
	<input type="hidden" name="ubicacion" value="-">

	<label class="control-label col-xs-12 col-sm-3 no-padding-right">Nombres:</label>

	<div class="col-xs-12 col-sm-7">
	<div class="col-sm-6">
	<input type   ="text" name="nombre" id="nombre" placeholder="Primer Nombre" class="form-control" />
	</div>
	<div class="col-sm-6">
	<input type   ="text" name="nombre2" id="nombre2" placeholder="Segundo Nombre" class="form-control" />
	</div>										
	</div>
	</div>

	<div class="space-2"></div>

	<div class="form-group">
	<label class="control-label col-xs-12 col-sm-3 no-padding-right">Apellidos:</label>

	<div class="col-xs-12 col-sm-7">
	<div class="col-sm-6">
	<input type   ="text" name="apellido" id="apellido" placeholder="Primer apellido" class="form-control" />
	</div>
	<div class="col-sm-6">
	<input type   ="text" name="apellido2" id="apellido2" placeholder="Segundo apellido" class="form-control" />
	</div>										
	</div>
	</div>									
	<div class="form-group" align="center">	
	<div>
	<label class="control-label col-sm-3 no-padding-right" for="sexo">Sexo:</label>
	</div>
	<div class="col-sm-1">
	<div class="clearfix">
	<div>
	<label class="line-height-1 blue">
	<input  value="16" type="radio" class="ace" name="sexos" />
	<span class="lbl"> Masculino</span>
	</label>
	</div>
	</div>
	</div>
	<div class="col-sm-1">
	<div class="clearfix">
	<div>
	<label class="line-height-1 blue">
	<input  value="17" type="radio" class="ace" name="sexos" />
	<span class="lbl"> Femenino</span>
	</label>
	</div>
	</div>
	</div>																			
	</div>	
	<div align="center">
	<button class="btn btn-primary" onclick="send_consulta_hijo();showElementos('tablaHijos');">
	<i class      ="ace-icon fa fa-floppy-o fa-lg"></i>
	Registrar
	</button>
	</div>
	</div><!--  Fin informacion de los hijos -->			
	<hr>
	<div id="tablaHijos" hidden>
	<table id="dynamic-table" class="table table-striped table-bordered table-hover">
	<thead>
	<tr>
	<th class="center">
	<label class="pos-rel">
	#
	</label>
	</th>
	<th>Cedula</th>
	<th>Primer nombre</th>
	<th class="hidden-480">Segundo nombre</th>
	<th>Primer apellido</th>
	<th class="hidden-480">Segundo apellido</th>
	<th class="center">Acciones</th>
	</tr>
	</thead>

	<tbody>
	<?php foreach ($this->_listado as $persona): ?>
	<tr>
	<td class="center">
	<?php echo $persona['numeracion'];?>
	</td>

	<td>
	<?php echo $persona['cedula']; ?>
	</td>
	<td><?php echo $persona['nombre']; ?></td>
	<td class="hidden-480"><?php echo $persona['nombre2']; ?></td>
	<td><?php echo $persona['apellido']; ?></td>

	<td class="hidden-480">
	<?php echo $persona['apellido2']; ?>
	</td>

	<td class="center">
	<div class="hidden-sm hidden-xs action-buttons">
	<a class="btn-app  btn-primary  btn-sm" id="detalle_persona" 
	onclick="pickOpen('prod', 'id_prod', 
	'<?php echo BASE_URL."personal/update/". $persona['id_persona'] ?>',
	90, 80, 70, 50);show('prod',500);show('id_aceptar',500);hide('id_buscar',500);"
	style=cursor:pointer; >
	<i class="glyphicon glyphicon-search"></i>
	Detalles

	</a>		

	<a class="btn-app btn-danger btn-sm" href="<?php echo BASE_URL."personal/delete/". $persona['id_persona'] ?>">
	<i class="ace-icon fa fa-trash-o bigger fa-lg"></i>
	Eliminar
	</a>	
	</div>

	</td>
	</tr>
	<?php endforeach ?>
	</tbody>  <!-- div tabla  -->
	</table>											
	</div>	<!-- final div tabla			 -->										

	</div>
	<hr>

	</div>

	<div class="step-pane" data-step="3">
	<div class="center">

	</div>
	</div>

	<div class="step-pane" data-step="4">
	<div class="center">
	<h3 class="green">Congrats!</h3>
	Your product is ready to ship! Click finish to continue!
	</div>
	</div>
	</div>
	</div>

	<hr />
	<div class="wizard-actions">
	<button class="btn btn-prev">
	<i class="glyphicon-plus"></i>
	Registrar a otra persona.
	</button>

	<button class="btn btn-success btn-next" data-last="Finish" onclick="send_registro_persona()">
	Siguiente
	<i class="ace-icon fa fa-arrow-right icon-on-right"></i>
	</button>
	</div>
	</div><!-- /.widget-main -->
	</div><!-- /.widget-body -->
	</div>

</form>											
</div><!-- /.page-content -->

