<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
	<div class="main-content-inner">

<form class   ="form-inline center" role="form"  method="post"  id="registro_persona" name="registro_persona" >
	
	
	<div class="widget-box">
		<div class="alert alert-info ">

			<div class  id="inicio" align="center">
				<h4 class="widget-title">Registro de persona.</h4>
			</div>

			<div id="infoDatosDiv" hidden="" >
				<div  class="col-sm-3">
					<h5 class="widget-title">Registrando datos de:</h5>
					<table id="infoDatos">
						<td class="center" ></td>
					</table>
					
				</div>
				<br>
				<br>
				<br>
			</div>
		</div>
		<div class="widget-body">
			<div class="widget-main">
				<div id="my-wizard">
					<div>
						<ul class="steps">
							<li data-step="1" class="active">
								<span class="step" style=cursor:pointer;>1</span>
								<span class="title">Datos personales</span>
							</li>
							
							<li data-step="2">
								<span class="step" style=cursor:pointer;>2</span>
								<span class="title">Información de los hijos</span>
							</li>
							
							<li data-step="3">
								<span class="step" style=cursor:pointer;>3</span>
								<span class="title">Información de los padres</span>
							</li>
							
							<li data-step="4">
								<span class="step" style=cursor:pointer;>4</span>
								<span class="title">Otra información</span>
							</li>
						</ul>
					</div>
					<br>
					<div class="step-content pos-rel">
						<div class="step-pane active" data-step="1" id="divPersona">
							<input type="text" name="tipo_persona" value="empleada" hidden></input>
							    <div class="form-group">
								<label for="cedula">Cédula: </label>
											<input onkeypress="return numeros(event);" maxlength="10" onkeyup="format(this)" autocomplete="off" type   ="text" name="cedula" id="cedula" class="input-sm form-control" />
							    </div>

							    <div class="form-group">
										<div class="input-group">
											<a class="btn btn-primary" onclick="obten_datos('cedula','nombre','nombre2','apellido','apellido2','fecha_nacimiento','telefono','fecha_ingreso','correo','ubicacion','direccion');">
												Buscar en SIGESP
												<i class="glyphicon glyphicon-search"></i>
											</a>
										</div>
							    </div>
							    <hr>
							<div class="form-group">
								<label class="control-label ">Nombres:</label>
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="nombre" id="nombre" placeholder="Primer Nombre" class="input-sm form-control"/>
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="nombre2" id="nombre2" placeholder="Segundo Nombre" class="input-sm form-control" />
							</div>
							<div class="space-2"></div>
							
							<div class="form-group">
								<label class="control-label">Apellidos:</label>
								
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="apellido" id="apellido" placeholder="Primer apellido" class="input-sm form-control" />
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="apellido2" id="apellido2" placeholder="Segundo apellido" class="input-sm form-control" />
							</div>

							<hr>
							<div class="form-group">							
											<label class="control-label" for="sexo">Sexo:</label>
											<div class="radio">
											<label class="line-height-1 blue">
												<input autocomplete="off"  value="16" type="radio" class="ace" name="sexos" 
												/>
												<span class="lbl"> Masculino</span>
											</label>												
											</div>
											<div class="radio">
											<label class="line-height-1 blue">
												<input autocomplete="off"  value="17" type="radio" class="ace" name="sexos" />
												<span class="lbl"> Femenino</span>
											</label>												
											</div>

								
							</div>	
							&nbsp;&nbsp;
							<div class="form-group">
								<label class="control-label" for="fecha_nacimiento">Fecha de nacimiento: </label>
										<input  onkeypress="return letras(event)" autocomplete="off" class  ="input-sm form-control date-picker" name="fecha_nacimiento" id="fecha_nacimiento" type="date" data-date-format="yyyy-mm-dd" size="8" />							
							</div>	
							&nbsp;	&nbsp;
							<div class="form-group">
								<label class="control-label" for="cedula">Fecha de ingreso: </label>
											<input onkeypress="return numeros(event);" onkeypress="return letras(event)" autocomplete="off" class  ="input-sm form-control date-picker" name="fecha_ingreso" id="fecha_ingreso" type="date" data-date-format="yyyy-mm-dd" size="8" />
							</div>	
							<hr>																	
							<div class="form-group">
								<label class="control-label" for="cedula">Télefono: </label>
											<input autocomplete="off" class  ="input-sm form-control input-mask-phone" type="text" id="telefono" name="telefono" size="12"/>
							</div>
							<div class="form-group">
										<label class="control-label" for="cedula">Otro télefono: </label>
													<input autocomplete="off" class  ="input-sm form-control input-mask-phone" type="text" id="otro_telefono" name="otro_telefono" size="12"/>
							</div>	
							<div class="form-group">
										<label class="control-label" for="cedula">Correo personal: </label>
													<input autocomplete="off" class  ="input-sm form-control" type="text"  name="correo" id="correo" size="30"/>

							</div>
							<hr>
							<div align="center" class="form-group">
								<label class="control-label" for="estado">Cargo: </label>
									<select name="cargo" id="cargo" class="selectpicker show-tick input-sm form-control">
									</select>
							</div>							
							<div align="center" class="form-group">
								<label class="control-label" for="coordinacion">Coordinación: </label>
									<select name="coordinacion" id="coordinacion" class="selectpicker show-tick input-sm form-control">
									</select>
							</div>
								<hr>
							<div align="center" class="form-group">
								<label class="control-label" for="estado">Estado: </label>
									<select name="estado" id="estado" class="selectpicker show-tick input-sm form-control" data-live-search="true">
									</select>
							</div>
							
							<div align="center" class="form-group">
								<label class="control-label" for="municipio">Municipio: </label>
									<select name="municipio" id="municipio" class="selectpicker show-tick input-sm form-control" data-live-search="true">
									</select>
							</div>
							
							<div align="center" class="form-group">
								<label class="control-label" for="parroquia">Parroquia: </label>
									<select name="direccion" id="direccion" class="selectpicker show-tick input-sm form-control" data-live-search="true">
									</select>
							</div>
							<br><hr>
							<div class="form-group">
								<label class="control-label" for="ubicacion">Ubicación: </label>
											<input autocomplete="off" class  ="input-sm form-control" type="text" id="ubicacion" name="ubicacion" placeholder="Zona donde vive la persona" size="80" />
						
							</div>							
							<div  id="modificarDatos" hidden align="center">
								<button class="btn btn-primary">
								Actualizar
								<i class="glyphicon glyphicon-search"></i>
								</button>
							</div>
						</form>
					</div>
					
					<div class="step-pane" data-step="2">
						<div>
							<div id="infoExtra" >
								<hr>
								<h3 align="center" class="lighter block blue">Ahora podrá registrar un máximo de 5 hijos</h3>
							</div>
							<div id="infoHijos" class="col-sm-16"><!-- informacion de los hijos -->
							
								<br>
								
								<div class="form-group">
									<input type="text" name="tipo_persona" value="hijo" hidden></input>
									<input autocomplete="off" type="hidden" name="cedula" value="-">
									<input autocomplete="off" type="hidden" name="fecha_ingreso" value="2016-01-01">
									<input autocomplete="off" type="hidden" name="telefono" value="-">
									<input autocomplete="off" type="hidden" name="otro_telefono" value="-">
									<input autocomplete="off" type="hidden" name="correo" value="-">
									<input autocomplete="off" type="hidden" name="direccion" value="0">
									<input autocomplete="off" type="hidden" name="ubicacion" value="-">
									<input autocomplete="off" type="hidden" name="cargo" value="0">
									<input autocomplete="off" type="hidden" name="coordinacion" value="0">
								</div>
							<div class="form-group">
								<label class="control-label ">Nombres:</label>
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="nombre" id="nombre" placeholder="Primer Nombre" class="input-sm form-control"/>
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="nombre2" id="nombre2" placeholder="Segundo Nombre" class="input-sm form-control" />
							</div>
							<div class="space-2"></div>
							
							<div class="form-group">
								<label class="control-label">Apellidos:</label>
								
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="apellido" id="apellido" placeholder="Primer apellido" class="input-sm form-control" />
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="apellido2" id="apellido2" placeholder="Segundo apellido" class="input-sm form-control" />
							</div>					<br>	<br>		
							<div class="form-group">							
											<label class="control-label" for="sexo">Sexo:</label>
											<div class="radio">
											<label class="line-height-1 blue">
												<input autocomplete="off"  value="16" type="radio" class="ace" name="sexos" 
												/>
												<span class="lbl"> Masculino</span>
											</label>												
											</div>
											<div class="radio">
											<label class="line-height-1 blue">
												<input autocomplete="off"  value="17" type="radio" class="ace" name="sexos" />
												<span class="lbl"> Femenino</span>
											</label>												
											</div>

								
							</div>	
							&nbsp;&nbsp;
							<div class="form-group">
								<label class="control-label" for="fecha_nacimiento">Fecha de nacimiento: </label>
										<input  onkeypress="return letras(event)" autocomplete="off" class  ="input-sm form-control date-picker" name="fecha_nacimiento" id="fecha_nacimiento_hijo" type="date" data-date-format="yyyy-mm-dd" size="8" />							
							</div>	
														<hr>

								<div align="center">
									<button class="btn btn-success" onclick="send_consulta_hijo();send_registro_persona('empleada');" id="registrarHijo">
									<i class      ="ace-icon fa fa-floppy-o fa-lg"></i>
									Registrar
									</button>
									<br><br><br><br><br><br><br><br>
								</div>
								<hr>
							</div><!--  Fin informacion de los hijos -->
							<div align="center" id="AgregarOtro" hidden>
								<button class="btn btn-primary" onclick="showElementos('infoHijos');hiddenElementos('AgregarOtro');">
								<i class      ="glyphicon glyphicon-plus"></i>
								Agregar otro hijo
								</button>
							</div>
							<div id="tablaHijos" hidden="">									
										<div id="tabla_consulta" align="center" class="widget-box">
												<table  id="tablaInfoHijos"></table>
												<div id="tablaInfoHijosDiv"></div>
										</div>
							</div>			
							</div>
						<hr>						
					</div>
							
							<div class="step-pane" data-step="3">
								<div>
									
									<div id="preguntaPadresAmbos" >
												<div id="pregunta">
													<label for="">Si esta persona tiene sus padres vivos seleccione una opción</label>
												</div>
												<div id="continuar" hidden="">
													<label for="">Puede omitir este registro</label>
												</div>												
												<label class="blue">
													<input autocomplete="off"  value="16" type="radio" class="ace" name="Padres"
													onchange="showElementos('infoPadresAmbos');hiddenElementos('infoPadreUnico');hiddenElementos('saltos');hiddenElementos('pregunta');showElementos('continuar');" value="16" />
													<span class="lbl"> Ambos</span>
												</label>
											
												<label class="blue">
													<input autocomplete="off"  value="16" type="radio" class="ace" name="Padres" onchange="hiddenElementos('infoPadresAmbos');showElementos('infoPadreUnico');hiddenElementos('saltos');hiddenElementos('pregunta');showElementos('continuar');" />
													<span class="lbl"> Solo uno de ellos</span>
												</label>
									
									<div id="saltos">
									<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
										
									</div>
								</div>
								<hr>
								
								<div id="infoPadresAmbos" class="col-sm-16" hidden><!-- informacion de los Padres -->
									<h3 align="center" class="lighter block blue">Información del padre de la persona</h3>
									<br>
									<div id="infoPadre">
										<input type="text" name="tipo_persona" value="padre" hidden></input>
										<input autocomplete="off" type="hidden" name="cedula" value="-">
										<input autocomplete="off" type="hidden" name="fecha_ingreso" value="2016-01-01">
										<input autocomplete="off" type="hidden" name="fecha_nacimiento" value="2016-01-01">
										<input autocomplete="off" type="hidden" name="telefono" value="-">
										<input autocomplete="off" type="hidden" name="otro_telefono" value="-">
										<input autocomplete="off" type="hidden" name="correo" value="-">
										<input autocomplete="off" type="hidden" name="direccion" value="0">
										<input autocomplete="off" type="hidden" name="ubicacion" value="-">
										<input autocomplete="off" type="hidden" name="sexos" value="0">
							<div class="form-group">
								<label class="control-label ">Nombres:</label>
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="nombre" id="nombre" placeholder="Primer Nombre" class="input-sm form-control"/>
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="nombre2" id="nombre2" placeholder="Segundo Nombre" class="input-sm form-control" />
							</div>
							<div class="space-2"></div>
							
							<div class="form-group">
								<label class="control-label">Apellidos:</label>
								
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="apellido" id="apellido" placeholder="Primer apellido" class="input-sm form-control" />
										<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
										type   ="text" name="apellido2" id="apellido2" placeholder="Segundo apellido" class="input-sm form-control" />
							</div>					<br>	<br>		
									<div class="form-group">
										<label class="control-label" for="cedula">Télefono: </label>
													<input autocomplete="off" class  ="input-sm form-control input-mask-phone" type="text" id="telefono" name="telefono" size="12"/>
									</div>

									</div>
									<hr>
									<br>
									<h3 align="center" class="lighter block blue">Información de la madre de la persona</h3>
									<div id="infoMadre">
										<input autocomplete="off" type="hidden" name="cedula" value="-">
										<input autocomplete="off" type="hidden" name="fecha_ingreso" value="2016-01-01">
										<input autocomplete="off" type="hidden" name="fecha_nacimiento" value="2016-01-01">
										<input autocomplete="off" type="hidden" name="telefono" value="-">
										<input autocomplete="off" type="hidden" name="otro_telefono" value="-">
										<input autocomplete="off" type="hidden" name="correo" value="-">
										<input autocomplete="off" type="hidden" name="direccion" value="0">
										<input autocomplete="off" type="hidden" name="ubicacion" value="-">
										<input autocomplete="off" type="hidden" name="sexos" value="0">
											<div class="form-group">
												<label class="control-label ">Nombres:</label>
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="nombre" id="nombre" placeholder="Primer Nombre" class="input-sm form-control"/>
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="nombre2" id="nombre2" placeholder="Segundo Nombre" class="input-sm form-control" />
											</div>
											<div class="space-2"></div>
											
											<div class="form-group">
												<label class="control-label">Apellidos:</label>
												
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="apellido" id="apellido" placeholder="Primer apellido" class="input-sm form-control" />
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="apellido2" id="apellido2" placeholder="Segundo apellido" class="input-sm form-control" />
											</div>					<br>	<br>		
							<div class="form-group">
								<label class="control-label" for="cedula">Télefono: </label>
											<input autocomplete="off" class  ="input-sm form-control input-mask-phone" type="text" id="telefono" name="telefono" size="12"/>
							</div>
							<hr>
									</div>
									<div align="center">
										<button class="btn btn-success" onclick="send_consulta_hijo();
										showElementos('tablaPadres');hiddenElementos('infoPadres');hiddenElementos('infoExtra');showElementos('AgregarOtroPadre');
										send_registro_persona('hijo')">
										<i class      ="ace-icon fa fa-floppy-o fa-lg"></i>
										Registrar
										</button>
									</div>
								</div><!--  Fin informacion de los Padres -->
																					
								<div id="infoPadreUnico" class="col-sm-16" hidden><!-- informacion infoPadreUnico -->
											<hr>	
											<br>											
											<div class="form-group">
												<input autocomplete="off" type="hidden" name="cedula" value="-">
												<input autocomplete="off" type="hidden" name="fecha_ingreso" value="2016-01-01">
												<input autocomplete="off" type="hidden" name="fecha_nacimiento" value="2016-01-01">
												<input autocomplete="off" type="hidden" name="telefono" value="-">
												<input autocomplete="off" type="hidden" name="otro_telefono" value="-">
												<input autocomplete="off" type="hidden" name="correo" value="-">
												<input autocomplete="off" type="hidden" name="direccion" value="0">
												<input autocomplete="off" type="hidden" name="ubicacion" value="-">
												<input autocomplete="off" type="hidden" name="sexos" value="0">
											</div>													
											<div class="form-group">
												<label class="control-label ">Nombres:</label>
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="nombre" id="nombre" placeholder="Primer Nombre" class="input-sm form-control"/>
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="nombre2" id="nombre2" placeholder="Segundo Nombre" class="input-sm form-control" />
											</div>
											<div class="space-2"></div>
											
											<div class="form-group">
												<label class="control-label">Apellidos:</label>
												
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="apellido" id="apellido" placeholder="Primer apellido" class="input-sm form-control" />
														<input style="text-transform: capitalize;" onkeypress="return letras(event)" autocomplete="off"
														type   ="text" name="apellido2" id="apellido2" placeholder="Segundo apellido" class="input-sm form-control" />
											</div>					<br>	<br>		
											<div class="form-group">
												<label class="control-label" for="cedula">Télefono: </label>
															<input autocomplete="off" class  ="input-sm form-control input-mask-phone" type="text" id="telefono" name="telefono" size="12"/>
											</div>
											<hr>
											<div align="center">
												<button class="btn btn-success" onclick="send_consulta_hijo();
												showElementos('tablaPadres');hiddenElementos('infoPadres');hiddenElementos('infoExtra');showElementos('AgregarOtroPadre');
												send_registro_persona('padre')">
												<i class      ="ace-icon fa fa-floppy-o fa-lg"></i>
												Registrar
												</button>
											</div>
											<br><br><br><br><br><br><br><br><br>
											<hr>
								</div><!--  Fin infoPadreUnico -->
								
								<div align="center" id="AgregarOtroPadre" hidden>
									<button class="btn btn-success" onclick="showElementos('infoPadres');hiddenElementos('AgregarOtroPadre');">
									<i class      ="glyphicon glyphicon-plus"></i>
									Agregar padre
									</button>
								</div>
								<div id="tablaPadres" hidden>
									<br>
									<table id="tablaPadresAdd" class="table table-striped table-bordered table-hover">
										<thead>
											<tr>
												<th>Primer nombre</th>
												<th class="hidden-480">Segundo nombre</th>
												<th>Primer apellido</th>
												<th class="hidden-480">Segundo apellido</th>
												<th class="center">Sexo</th>
												<th class="center">Edad</th>
											</tr>
										</thead>
										
										<tbody>
											<?php foreach ($this->_listado as $persona): ?>
											<tr>
												
												<!-- 	<td class="center">
													<div class="hidden-sm hidden-xs action-buttons">
																			<a class="btn-app  btn-primary  btn-sm" id="detalle_persona"
																									onclick="pickOpen('prod', 'id_prod',
															'<?php echo BASE_URL."personal/update/". $persona['id_persona'] ?>',
															90, 80, 70, 50);show('prod',500);show('id_aceptar',500);hide('id_buscar',500);"
															style=cursor:pointer; >
															<i class="glyphicon glyphicon-search"></i>
															Detalles
															
														</a>
														
														<a class="btn-app btn-danger btn-sm" href="<?php echo BASE_URL."personal/delete/". $persona['id_persona'] ?>">
															<i class="ace-icon fa fa-trash-o bigger fa-lg"></i>
															Eliminar
														</a>
													</div>
													
												</td> -->
											</tr>
											<?php endforeach ?>
											</tbody>  <!-- div tabla  -->
									</table>
								</div>	<!-- final div tabla			 -->
							</div>
									<hr>
									
							</div>
								
								<div class="step-pane" data-step="4">
									<div class="informacion_adicional" id="informacion_adicional">
										<div class="center">
											<div>
											
															
													
															
															<div>
															<label for="">¿Esta persona tiene vehículos?</label>
															</div>
															<label class="blue">
																<input autocomplete="off" type="radio" class="ace" name="vehiculos"
																onchange="" value="si" />
																<span class="lbl"> Si</span>
															</label>
														
															<label class="blue">
																<input autocomplete="off" value="no" type="radio" class="ace" name="vehiculos"  onchange=""/>
																<span class="lbl"> No</span>
															</label>
																<div>
																<label for="">Tipo de vivienda</label>
																</div>												
															<label class="blue">
																<input autocomplete="off" type="radio" class="ace" name="vivienda"
																onchange="" value="73" />
																<span class="lbl"> Alquilada</span>
															</label>
															&nbsp;
															<label class="blue">
																<input autocomplete="off" value="74" type="radio" class="ace" name="vivienda"  onchange=""/>
																<span class="lbl"> Propia</span>
															</label>

												</div>
												<hr>
												<div>

																
																<div>
																	<label for="">¿Practica algún deporte?</label>
																</div>
																
																<label class="blue">
																	<input autocomplete="off" type="radio" class="ace" name="deporte"
																	onchange="showElementos('deporteSelect');" />
																	<span class="lbl"> Si</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="no" type="radio" class="ace" name="deporte" onchange="hiddenElementos('deporteSelect');borrarCheckbox();"/>
																	<span class="lbl"> No</span>
																</label>

												</div>
												<div class="space-2"></div>
												<div id="deporteSelect" hidden>
																<div>
																	<label for="">Deportes que practica</label>
																</div>
																

																<label class="blue">
																	<input autocomplete="off" type="checkbox" id="check1" class="ace" name="<?php echo 'check0'; ?>"
																	onchange="" value="65" id="deporte"/>
																	<span class="lbl"> Fútbol</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="66" id="check2" type="checkbox" class="ace" name="<?php echo 'check1' ?>" onchange=""/>
																	<span class="lbl"> Basquet</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="67" id="check3" type="checkbox" class="ace" name="<?php echo 'check2' ?>" onchange=""/>
																	<span class="lbl"> Boleyball</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="68" id="check4" type="checkbox" class="ace" name="<?php echo 'check3' ?>" onchange=""/>
																	<span class="lbl"> Beisbol</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="69" id="check5" type="checkbox" class="ace" name="<?php echo 'check4'?>" onchange=""/>
																	<span class="lbl"> Softball</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="70" id="check6" type="checkbox" class="ace" name="<?php echo 'check5' ?>" onchange=""/>
																	<span class="lbl"> Ajedrez</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="80" id="check7" type="checkbox" class="ace" name="<?php echo 'check6' ?>" onchange=""/>
																	<span class="lbl"> Otro</span>
																</label>

												</div>
												<hr>
												<div>
																<div>
																	<label for="">¿Esta persona toma algún medicamento de por vida?</label>
																</div>
																

																<label class="blue">
																	<input autocomplete="off" type="radio" class="ace" name="medicina"
																	onchange="showElementos('medicamentos');"/>
																	<span class="lbl"> Si</span>
																</label>
																<label class="blue">
																	<input autocomplete="off" value="no" type="radio" class="ace" name="medicina" onchange="hiddenElementos('medicamentos');"/>
																	<span class="lbl"> No</span>
																</label>
												</div>
												<div id="medicamentos" hidden>
													<hr>
																<div>
																	<label for="">Medicamentos que toma esta persona:</label>
																</div>
																

																<textarea id="form-field-11" align"center" class="autosize-transition input-sm form-control" name="medicina_text"></textarea>

												</div>
											</div>
										</div>
									</div>
								</div>
				</div>
							
				<div class="wizard-actions">
					<button class="btn btn-prev">
					<i class="ace-icon fa fa-arrow-left"></i>
					Modificar datos
					</button>
					
					<button class="btn btn-success btn-next" data-last="Finalizar" onclick="
					hiddenElementos('inicio');">
					Siguiente
					<i class="ace-icon fa fa-arrow-right icon-on-right"></i>
					</button>
				</div>
	</div>
</form>

</div>
</div>
</div>
</div>
