<?php ob_start(); ?>
<style>
.CSSTableGenerator {
    margin:0px;padding:0px;
    width:100%;
    border:1px solid #000000;
    
    -moz-border-radius-bottomleft:0px;
    -webkit-border-bottom-left-radius:0px;
    border-bottom-left-radius:0px;
    
    -moz-border-radius-bottomright:0px;
    -webkit-border-bottom-right-radius:0px;
    border-bottom-right-radius:0px;
    
    -moz-border-radius-topright:0px;
    -webkit-border-top-right-radius:0px;
    border-top-right-radius:0px;
    
    -moz-border-radius-topleft:0px;
    -webkit-border-top-left-radius:0px;
    border-top-left-radius:0px;
}.CSSTableGenerator table{
    border-collapse: collapse;
        border-spacing: 0;
    width:100%;
    height:100%;
    margin:0px;padding:0px;
}.CSSTableGenerator tr:last-child td:last-child {
    -moz-border-radius-bottomright:0px;
    -webkit-border-bottom-right-radius:0px;
    border-bottom-right-radius:0px;
}
.CSSTableGenerator table tr:first-child td:first-child {
    -moz-border-radius-topleft:0px;
    -webkit-border-top-left-radius:0px;
    border-top-left-radius:0px;
}
.CSSTableGenerator table tr:first-child td:last-child {
    -moz-border-radius-topright:0px;
    -webkit-border-top-right-radius:0px;
    border-top-right-radius:0px;
}.CSSTableGenerator tr:last-child td:first-child{
    -moz-border-radius-bottomleft:0px;
    -webkit-border-bottom-left-radius:0px;
    border-bottom-left-radius:0px;
}.CSSTableGenerator tr:hover td{
    background-color:#ffffff;
        

}
.CSSTableGenerator td{
    vertical-align:middle;
    
    background-color:#ffffff;

    border:1px solid #000000;
    border-width:0px 1px 1px 0px;
    text-align:center;
    padding:5px;
    font-size:11px;
    font-family:Helvetica;
    font-weight:bold;
    color:#000000;
}.CSSTableGenerator tr:last-child td{
    border-width:0px 1px 0px 0px;
}.CSSTableGenerator tr td:last-child{
    border-width:0px 0px 1px 0px;
}.CSSTableGenerator tr:last-child td:last-child{
    border-width:0px 0px 0px 0px;
}
.CSSTableGenerator tr:first-child td{
        background:-o-linear-gradient(bottom, #005fbf 5%, #003f7f 100%);    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #005fbf), color-stop(1, #003f7f) );
    background:-moz-linear-gradient( center top, #005fbf 5%, #003f7f 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#005fbf", endColorstr="#003f7f");  background: -o-linear-gradient(top,#005fbf,003f7f);

    background-color:#005fbf;
    border:0px solid #000000;
    text-align:center;
    border-width:0px 0px 1px 1px;
    font-size:15px;
    font-family:Arial;
    font-weight:bold;
    color:#ffffff;
}
.CSSTableGenerator tr:first-child:hover td{
    background:-o-linear-gradient(bottom, #005fbf 5%, #003f7f 100%);    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #005fbf), color-stop(1, #003f7f) );
    background:-moz-linear-gradient( center top, #005fbf 5%, #003f7f 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#005fbf", endColorstr="#003f7f");  background: -o-linear-gradient(top,#005fbf,003f7f);

    background-color:#005fbf;
}
.CSSTableGenerator tr:first-child td:first-child{
    border-width:0px 0px 1px 0px;
}
.CSSTableGenerator tr:first-child td:last-child{
    border-width:0px 0px 1px 1px;
}
table {
    border-collapse: collapse;
}

table, th, td {
    border: 1px solid black;
}
</style>
<table id="dynamic-table" align="center" class="CSSTableGenerator">
<thead>
<tr >
<th > # </th>
<th>Primer nombre</th>
<th >Segundo nombre</th>
<th>Primer apellido</th>
<th >Segundo apellido</th>
<th >Cedula</th>
</tr>
</thead>

<tbody>
<?php foreach ($this->_listado as $persona): ?>
<tr>
<td align="center">
<?php echo $persona['numeracion'];?>
</td>

<td align="center"><?php echo $persona['nombre']; ?></td>
<td align="center"><?php echo $persona['nombre2']; ?></td>
<td align="center"><?php echo $persona['apellido']; ?></td>
<td align="center"><?php echo $persona['cedula']; ?></td>
<td align="center">
<?php echo $persona['apellido2']; ?>
</td>

</tr>
<?php endforeach ?>
</tbody>
</table>
    

<?php
//require_once("dompdf/dompdf_config.inc.php");
// $dompdf = new DOMPDF();
// $dompdf->load_html(ob_get_clean());
// $dompdf->render();
// $pdf = $dompdf->output();
// $filename = "listaDelPersonal";
// file_put_contents($filename, $pdf);
// $dompdf->stream($filename);

?>