<body class   ="no-skin">
	
	<div class    ="page-content">
		<div class    ="page-header">
			<h1>Registro de vacaciones asignadas</h1>
		</div>
		<h1>
		<small>
		<i class="ace-icon fa fa-angle-double-right"></i>
		Seleccione la(s) persona(s).
		</small>
		</h1>
		
		
		
		<!-- /.page-header -->
		<div class    ="row">
			<div class    ="col-xs-12">
				
				<!-- PAGE CONTENT BEGINS -->
				<form class   ="form-horizontal" role="form" action="<?php  echo BASE_URL;?>personal/insert" method="post" >
					
					<table id="dynamic-table" class="table table-striped table-bordered table-hover">
						<thead>
							<tr>
								<th >#</th>
								<th >Cedula</th>
								<th >Nombre</th>
								<th >Apellido</th>
								<th >Telefono</th>
								<th >Correo</th>
								<th > &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;Asignar</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->_listado as $persona): ?>
							<tr>
								<input type="hidden" value="<?php echo $persona['id_persona'];?>">
								<td ><?php echo $persona['numeracion'];?></td>
								<td ><?php echo $persona['cedula']; ?></td>
								<td ><?php echo $persona['nombre']; ?></td>
								<td ><?php echo $persona['apellido']; ?></td>
								<td ><?php echo $persona['telefono']; ?></td>
								<td ></td>
								<td> &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;
									<a class="btn-app  btn-primary  btn-sm">
										<label class="pos-rel">
											<?php
											$contador=count($persona['id_persona']);
											for ($i=0; $i <$contador ; $i++):?>
											<input type="checkbox" class="ace" name="persona_asignada_<?php echo $i;?>"
											value="<?php echo $persona['id_persona'];?>"/>
											<?php endfor ?>
											<span class="lbl"></span>
										</label>
									</a>
								</td>
							</tr>
							<?php endforeach ?>
						</tbody>
					</table>
					<div>
						<br>
						<table align="center" >
							<!---- Labels ---->
							<tr>
								<td>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td>
								<td><label>Fecha de vacaciones:</label></td>
								<td>&nbsp; &nbsp;</td>
								<td><label>Dias habiles:</label></td>
								<td></td>
								<td>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td>
								<td><label>Fecha de reincorporación:</label></td>
							</tr>
							<!-- Fin de los Labels -->
							<!---------------------->
							<!---------------------->
							<!-- Inputs o selects -->
							<tr>
								<td> </td>
								<td>
									<div class="row">
										<div class="col-xs-8 col-sm-11">
											<div class="input-group">
												<span class="input-group-addon">
													<i class="fa fa-calendar bigger-110"></i>
												</span>
												<input class="form-control" type="text" name="date-range-picker" id="id-date-range-picker-1" size="30" />
											</div>
										</div>
									</div>
								</td>
								<td></td>
								<td>
									<div class    ="input-group">
										<span class   ="input-group-addon">
											<i class      ="fa fa-calendar-o"></i>
										</span>
										<input type   ="text"  name="dias_habiles" id="dias_habiles" size="5">
									</div>
								</td>
								<td></td>
								<td>&nbsp;</td>
								<td>
									<div class    ="input-group">
										<input class  ="form-control date-picker" name="fecha_reincorporacion" type="date" data-date-format="yyyy-mm-dd" />
										<span class   ="input-group-addon">
											<i class      ="fa fa-calendar bigger-110"></i>
										</span>
									</div>
								</td>
								
							</tr>
							<!------------Fin de los inputs------------>
							
						</table>
						<br>
						
					</div>
					
					<div class    ="space-24"></div>
					
					<hr />
					
					<div class    ="clearfix form-actions" align="center">
						<div>
							<button class ="btn btn-primary" type="submit">
							<i class      ="ace-icon fa fa-floppy-o fa-lg"></i>
							Guardar
							</button>
							
							&nbsp; &nbsp; &nbsp;
							<button class ="btn" type="reset">
							<i class      ="ace-icon fa fa-undo bigger-110"></i>
							Restaurar valores
							</button>
						</div>
					</div>
					
				</form>
				<!-- PAGE CONTENT ENDS -->
				</div><!-- /.col -->
				</div><!-- /.row -->
				</div><!-- /.page-content -->
			</div>
			</div><!-- /.main-content -->
		</body>
		
	</html>