	<div class="widget-box divBlanco">
		<div class="alert alert-info" align="center">
			<h4>Consulta de amonestaciones<i class="fa fa-users fa-lg"></i></h4>
		</div>
		<hr>
		<div class="row ">
				
			<div class="col-xs-12">
				<div class="row ">
					<div class="col-xs-12 ">
						<div class="table-header ">
							Personas con amonestaciones registradas.
						</div>
						<div>
							<form action="<?php  echo BASE_URL;?>personal/listing" method="post">
									<table id="dynamic-table" class="table table-striped table-bordered table-hover">
										<thead>
											<tr>
												<th class="center">
													<label class="pos-rel">
														#
													</label>
												</th>
												<th class="center">Fecha de solicitud</th>
												<th class="center">Dias habiles</th>
												<th class="center">Fecha de reincorporacion</th>
												<th class="center">Nombre y apellido de la persona</th>
												<th class="center">Coordinacion</th>
												<th class="center">Acciones</th>													
											</tr>
										</thead>
										<tbody>
											<?php foreach ($this->_listado as $persona): ?>
											<tr>
												<td class="center"><?php echo $persona['numeracion'];?></td>
												<td class="center"><?php echo $persona['fecha_solicitud'];?></td>										
												<td class="center" ><?php echo $persona['dias_correspondientes']; ?></td>
												<td class="center" ><?php echo $persona['reincorporacion']; ?></td>
												<td class="center" ><?php echo $persona['nombre']; ?>&nbsp;&nbsp;<?php echo $persona['nombre2']; ?></td>
												<td class="center" ><?php echo $persona['coordinacion']; ?></td>									
												<td class="center">
													<div class="hidden-sm hidden-xs action-buttons">	
														<a class="btn-app btn-eliminar btn-sm" href="<?php echo BASE_URL."personal/delete/". $persona['id_persona'] ?>">
														<i class="glyphicon glyphicon-remove-circle"></i>
															Cancelar
														</a>
													</div>
												</td>
											</tr>
											<?php endforeach ?>
										</tbody>
									</table>
								</div><!-- /.col -->
							</form>
						</div>
					</div>
				</div>
			</div>
				<br>	
			</div>
			
		<div id="prod"></div>
		<div id="resultado" align="center"></div>
		<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>