<div class="main-content" >
	<div class="main-content-inner">

	<!-- Slider -->
        <div id="main-slider" class="flexslider">
            <ul class="slides">
              <li>
                <img src="<?php echo PUBLIC_URL;?>img/slideReal.jpeg" alt="" />
              </li>
              <li>
                <img src="<?php echo PUBLIC_URL;?>img/slide1Real.jpg" alt="" />
              </li>
              <li>
                <img src="<?php echo PUBLIC_URL;?>img/slide3Real.jpg" alt="" />
              </li>
            </ul>
        </div>
	<!-- end slider -->


	</div>
</div>	