<div class="widget-box divBlanco">
	<div class="alert alert-info" align="center">
		<h4>Finalizar permiso <i class="fa fa-users fa-lg"></i></h4>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<div class="row">
				<div class="col-xs-12">
					<div>
						<form action="<?php  echo BASE_URL;?>permisos/finPermiso" method="post">
							<table id="dynamic-table" class="table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th >Persona asignada</th>
										<th >Coordinacion</th>
										<th >Permiso desde</th>
										<th >Hasta</th>
									</tr>
								</thead>
								<tbody>
									<?php foreach ($this->_datos as $permiso):?>
									<tr>
									<td ><?php echo $permiso['nombres']; ?></td>
									<td ><?php echo $permiso['coordinacion']; ?></td>
									<td ><?php echo $permiso['desde']; ?></td>
									<td ><?php echo $permiso['hasta']; ?></td>
									
									</tr>
							<input type="text" hidden value="<?php echo $permiso['id_permisos']; ?>" name="id_permiso"/>									
								<?php endforeach ?>
								</tbody>

							</table>


							</div><!-- /.col -->


			<div align="center">
				<div>
					<button class="btn btn-success" type="submit" onclick="closePickList()">
						<i class      ="ace-icon fa fa-floppy-o fa-lg"></i>
					Finalizar
					</button>
					&nbsp; &nbsp; &nbsp;			
					<a class="btn btn-primary" type="submit" onclick="closePickList()">
					<i class      ="fa fa-reply-all"></i>
					Salir
					</a>										
				</div>
			</div>
						</form>
					</div>
				</div>

		</div>
					</div>

		<br>
	</div>
	<div id="prod"></div>
	<div id="resultado" align="center"></div>
	<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>