<head>
	<link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/bootstrap-timepicker.min.css" />
	
	
</head>
<div class    ="page-content">
	<form action="<?php  echo BASE_URL;?>actividad_institucional/insert" method="post">
			<div class="page-header">
				<h1>
					Personal disponible para la actividad
					<small>
					<i class="ace-icon fa fa-angle-double-right"></i>
					Por favor agregue a las personas que asistiran a la actividad.
					</small>
				</h1>
			</div>
																				
				<table id="dynamic-table" class="table table-striped table-bordered table-hover">
								<thead>
										<tr>
										<th >#</th>
										<th >Nombre De La Actividad</th>
										<th >Fecha</th>
										<th >Hora</th>
										<th >Ubicación</th>
										<th colspan="100%">
											<div align="center">Acciones</div>
										</th>
										</tr>
								</thead>
								<tbody>
										<?php $cont=0; foreach ($this->_listado as $persona): $cont++;?>
										<tr>
										<td ><?php echo $persona['numeracion'];?></td>
										<td ><?php echo $persona['nombre_actividad']; ?></td>
										<td ><?php echo $persona['fecha_actividad']; ?></td>
										<td ><?php echo $persona['hora_actividad']; ?></td>
										<td ><?php echo $persona['ubicacion']; ?></td>
										<th> 
										<div align="center">
								<a class="btn-app  btn-primary  btn-sm" style=cursor:pointer;
								onclick="
								pickOpen('PickList', 'PickList', 
								'<?php echo BASE_URL."actividad_institucional/personasAsignadas/". $persona['id_actividad_institucional']?>', 90, 25, 80, 200);"
								>
										
											<i class="glyphicon glyphicon-search"></i>
												Detalles
												
											</a>																				
										</div>
										</th>
										<th><div align="center">
											<a class="btn-app btn-danger btn-sm" href="<?php echo BASE_URL."personal/delete/". $persona['id_actividad_institucional'] ?>">
												<i class="ace-icon fa fa-times bigger fa-lg"></i>

												Cancelar
											</a>											
										</div>
										</th>
										</tr>
										<?php endforeach ?>
								<input type="hidden" value="<?php echo $cont?>" name="contador"  >
							</tbody>
				</table>

	</form>
								<div id="PickList" style="width: 100%;display:none"></div>
			                    <div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>
</div>

