
<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
	<div class="main-content-inner">	
<div class="widget-box">
				<div class="alert alert-info" align="center">
					<h4>

					Consulta De Actividades </h4>
				</div>

					<div class="row">
							<div class="col-xs-12">
								<div class="row">
									<div id="tabla_consulta" class="col-xs-12">
										<!-- PAGE CONTENT BEGINS -->
									<table id="actividades"></table>
									<div id="pagerActividades"></div>
									<!-- PAGE CONTENT ENDS -->
									</div><!-- /.col -->
								</div>
							</div>
					</div><!-- /.row -->	
					<hr>
</div>

		<div id="prod"></div>
		<div id="resultado" align="center"></div>
		<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>
</div>
	</div>
</div>	
<!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido -->
