<div class="widget-box divBlanco">
	<div class="alert alert-info" align="center">

		<h4>Personas Asignadas A La Actividad: <?php echo $this->_actividad[0]['nombre_actividad'];?> <i class="fa fa-users fa-lg"></i></h4>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<div class="row">
				<div class="col-xs-12">
					<div>
						<form action="<?php  echo BASE_URL;?>personal/listing" method="post">
							<table class="table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th >#</th>
										<th >Nombres</th>
										<th >Coordinación</th>
										<th >Teléfono</th>
									</tr>
								</thead>
								<tbody>
									<?php $i=0; foreach ($this->_actividad as $persona): $i++;?>
									<tr>
										<td ><?php echo $persona['numeracion'];?></td>
										<td ><?php echo $persona['nombre'];?><?php echo $persona['apellido']; ?></td>
										<td ><?php echo $persona['coordinacion']; ?></td>
										<td ><?php echo $persona['telefono']; ?></td>
									</tr>
									<?php endforeach ?>
								</tbody>
							</table>
							
						</form>
					</div><!-- /.col -->
				</div>
			</div>

		</div>
	
	</div>
	<?php if($i==1):?>
	<br><br><br><br><br><br><br>
	<?php elseif($i==2):?>
	<br><br><br><br><br><br>
	<?php elseif($i==3):?>
	<br><br><br><br>
	<?php elseif($i==4):?>
	<br><br>
	<?php endif ?>
	<div  align="center">		
	<button class="btn btn-eliminar" onclick="closePickList()">
	<i class      ="fa fa-reply-all"></i>
	Salir
	</button>

	</div>	
		<br>
</div>
	<div id="prod"></div>
	<div id="resultado" align="center"></div>
	<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>