	<form action="<?php  echo BASE_URL;?>actividad_institucional/insert" method="post">
<table align="right">
					<td>
					<div align="right">
															<a class ="btn-app btn-danger btn-sm" 
															onclick="closePickList()" style=cursor:pointer;>
															<i class      ="ace-icon fa fa-times bigger fa-lg"></i>
															</a>	
					</div>
					</td>
</table>
<br><br>
		<hr>

																				
				<table id="dynamic-table" class="table table-striped table-bordered table-hover">
								<thead>
										<tr>
										<th >#</th>
										<th >Primer Nombre</th>
										<th >Segundo Nombre</th>
										<th >Primer Apellido</th>
										<th >Segundo Apellido</th>
										<th >Teléfono</th>
										</tr>
								</thead>
								<tbody>
										<?php foreach ($this->_listado as $persona):?>
										<tr>

										<td ><?php echo $persona['numeracion'];?></td>
										<td ><?php echo $persona['nombre'];?></td>
										<td ><?php echo $persona['nombre2']; ?></td>
										<td ><?php echo $persona['apellido']; ?></td>
										<td ><?php echo $persona['apellido2']; ?></td>
										<td ><?php echo $persona['telefono']; ?></td>
										</tr>
										<?php endforeach ?>
							</tbody>
				</table>
	</form>

</div>
