<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
        <title>CATIC</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <!-- bootstrap & fontawesome -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/font-awesome/4.2.0/css/font-awesome.min.css" />
        <!-- alert personalizado -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/wow-alert.css" />
        <!-- ace styles -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/form.css" />
        <?php if(isset($_view_params['css'])&&count($_view_params['css'])): ?>
        <?php for($i=0;$i<count($_view_params['css']);$i++): ?>
        <link rel="stylesheet" href="<?php echo $_view_params['css'][$i]; ?>" type="text/css" />
        <?php endfor; ?>
        <?php endif;?>
    </head>
   