<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
        <title>CATIC</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <!-- bootstrap & fontawesome -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/font-awesome/4.2.0/css/font-awesome.min.css" />
        <!-- page specific plugin styles -->
        <!-- text fonts -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/fonts/fonts.googleapis.com.css" />
        <!-- ace styles -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/tablas.css" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/wow-alert.css" />
        <!--[if lte IE 9]>
        <link rel="stylesheet" href="assets/css/ace-part2.min.css" class="ace-main-stylesheet" />
        <![endif]-->
        <!--[if lte IE 9]>
        <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
        <![endif]-->
        <!-- inline styles related to this page -->
        <!-- ace settings handler -->
        <script src="<?php echo PUBLIC_URL;?>js/actualizarPersona/actualizarPersona.js"></script>
        <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
        <!--[if lte IE 8]>
        <script src="assets/js/html5shiv.min.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/datepicker.min.css" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/daterangepicker.min.css" />
        <script src="<?php echo PUBLIC_URL;?>/js/reqs.js"></script>
        <script src="<?php echo PUBLIC_URL;?>/js/ajax.js"></script>
        <script src="<?php echo PUBLIC_URL;?>/js/validar.js"></script>
        <script src="<?php echo PUBLIC_URL;?>/js/tabla.js"></script>
        <script src="<?php echo PUBLIC_URL;?>/js/pickList.js"></script>
    </head>
   