	<div class="widget-box" id="caja">
		<div class="alert alert-info" align="center">
			<h4>Consulta del sistema biometrico <i class="fa fa-users fa-lg"></i></h4>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
					<div id="tabla_consulta" class="col-xs-12">
							<table id="consulta_biometrico"></table>
							<div id="jqGridPager"></div>
					</div>
				</div>
			</div>
		</div>
		<br><hr>
	</div>
	<br>
	<br>
<br>
	<br><br>
	<br>