<?php ob_start(); ?>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>Detalles completos de la persona</title>
     <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/pdf.css" />
</head>
<body>
 <script type="text/php">

        if ( isset($pdf) ) {
                $w = $pdf->get_width();
                $h = $pdf->get_height();
                $font = Font_Metrics::get_font("Arial", "bold");
                $pdf->page_text($w - 120, $h - 72, "Pagina: {PAGE_NUM} de {PAGE_COUNT}", $font, 11, array(0,0,0));  

        }

</script>  
<div class="cintillo">
        <img src="/var/www/html/catic/public/img/cintillo.jpg" width="100%" height="60">
</div> 
<div class="cuerpo">
    <div class="page-header" align="center">
        <h2>
        Datos completos de la persona
        </h2>
    </div>
    <table id="dynamic-table" align="center" class="CSSTableGenerator">

        <tr >
        <th class="center" >Cedula</th>
        <th class="center">Nombres</th>
        <th class="center">Apellidos</th>
        </tr>

        <tr>
        <td align="center"><?php echo $this->_persona[0]['cedula'] ?></td>
        <td align="center" ><?php echo $this->_persona[0]['nombre'] ?>&nbsp;<?php echo $this->_persona[0]['nombre2'] ?></td>
        <td align="center" ><?php echo $this->_persona[0]['apellido'] ?>&nbsp;<?php echo $this->_persona[0]['apellido2'] ?></td>
        </tr>

        <tr >
        <th class="center">Fecha de nacimiento</th>
        <th class="center">Edad</th>
        <th class="center">Correo</th>
        </tr>

        <tr>
        <td align="center"><?php echo $this->_persona[0]['fecha_nacimiento'] ?></td>
        <td align="center"><?php echo $this->_persona[0]['edad'] ?></td>
        <td align="center" ><?php echo $this->_persona[0]['correo'] ?></td>
        </tr>


        <tr>
        <th class="center">Telefonos</th>
        <th class="center">Edad</th>
        <th class="center">Sexo</th>
        </tr>
        <tr>
        <td align="center" ><?php echo $this->_persona[0]['telefono'] ?>*<?php echo $this->_persona[0]['otro_telefono'] ?></td>
        <td align="center"><?php echo $this->_persona[0]['edad'] ?></td>
        <td align="center"><?php echo $this->_persona[0]['sexo'] ?></td>
        </tr>
        <tr>
        <th class="center" >Fecha de ingreso</th>
        <th class="center">Coordinación</th>
        <th class="center">Cargo</th>
        </tr>
        <tr>
        <td align="center" ><?php echo $this->_persona[0]['fecha_ingreso'] ?></td>
        <td align="center" ><?php echo $this->_persona[0]['coordinacion'] ?></td>
        <td align="center">FALTA</td>
        </tr>
    </table>


    <div class="page-header" align="center">
        <h2>
        Dirección
        </h2>
    </div>
    <table id="dynamic-table" align="center" class="CSSTableGenerator">
        <tr >
        <th class="center" >Estado</th>
        <th class="center">Municipio</th>
        <th class="center">Parroquia</th>
        </tr>
        <tr>
        <td align="center"><?php echo $this->_persona[0]['estado'] ?></td>
        <td align="center" ><?php echo $this->_persona[0]['municipio'] ?></td>
        <td align="center" ><?php echo $this->_persona[0]['parroquia'] ?></td>
        </tr>
        </tr>
    </table>  
   <table id="dynamic-table" align="center" class="CSSTableGenerator">
        <tr >
        <th class="center" >Ubicación</th>
        </tr>
        <tr>
        <td align="center"><?php echo $this->_persona[0]['ubicacion'] ?></td>
        </tr>
    </table> 
    <?php if($this->_hijos!=null): ?>       
        <div class="page-header" align="center">
        <h2>
        Información de los hijos
        </h2>
    </div>
    <table id="dynamic-table" align="center" class="CSSTableGenerator">
        <tr >
        <th class="center" >Nombres</th>
        <th class="center">Apellidos</th>
        <th class="center">Fecha. Nac</th>
        <th class="center">Edad</th>
        <th class="center">Sexo</th>
        </tr>
        <tr>
        <td align="center"><?php echo $this->_hijos[0]['nombre'] ?>&nbsp;<?php echo $this->_hijos[0]['nombre2'] ?></td>
        <td align="center"><?php echo $this->_hijos[0]['apellido'] ?>&nbsp;<?php echo $this->_hijos[0]['apellido2'] ?></td>
        <td align="center" ><?php echo $this->_hijos[0]['fecha_nacimiento'] ?></td>
        <td align="center" ><?php echo $this->_hijos[0]['edad'] ?></td>
        <td align="center" ><?php echo $this->_hijos[0]['sexo'] ?></td>
        </tr>
        </tr>
    </table>
    <?php endif ?>  

    <?php if($this->_deporte!=null): ?>       
        <div class="page-header" align="center">
        <h2>
        Información adicional
        </h2>
    </div>
    <table id="dynamic-table" align="center" class="CSSTableGenerator">
        <tr >
        <th class="center">¿Posee vehiculo?</th>
        <th class="center">Tipo de vivienda</th>
        </tr> 
        <tr>
        <td align="center"><?php echo $this->_deporte[0]['vehiculo'] ?></td>
        <td align="center"><?php echo $this->_deporte[0]['vivienda'] ?></td>   
        </tr>       
    </table>
    <table id="dynamic-table" align="center" class="CSSTableGenerator">
        <tr >
        <th class="center" >Medicamentos que toma de por vida</th>
        </tr>
        <tr>
        <td align="center" ><?php echo $this->_deporte[0]['medicamentos'] ?></td>
        </tr>               
    </table> 
    <table id="dynamic-table" align="center" class="CSSTableGenerator">
        <tr >
        <th class="center" >Deportes que practica</th>
        </tr>
        <tr> 
        <td align="center">
        <?php foreach ($this->_deporte as $deporter => $valor): ?>
        <?php echo $valor[2] ?>&nbsp;
        <?php endforeach ?>
        </td> 
        </tr>               
    </table>        
    <?php endif ?>     
</div>


 <footer>
 <div align="center">
     <?php echo date("m/d/Y"); ?>
 </div>
 </footer>
   
</body>



    

<?php
$dompdf = new DOMPDF();
$dompdf->load_html(ob_get_clean());
$dompdf->render();
$pdf = $dompdf->output();
$dompdf->stream('Detalles_de:'. $this->_persona[0]['nombre'].'_'. $this->_persona[0]['apellido'],array('Attachment'=>0));
?>