<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
	<div class="main-content-inner">
<div class="widget-box">
		<div class="alert alert-info" align="center">
			<h4>Registro de fechas feriadas del año <i class="fa fa-users fa-lg"></i></h4>
		</div>
<form action="<?php  echo BASE_URL;?>administracion/registrarFechas" method="post" accept-charset="utf-8">
<div class="" align="center">
								
		<div class="col-sm-12">
		<label class="control-label " for="fechas">Fechas feriadas:</label>
			<div class="input-group">
				<input  onkeypress="return letras(event)" autocomplete="off" class  ="input-sm form-control date-picker" name="fechas" id="fechas" type="date" data-date-format="yyyy-mm-dd" />
				<span class   ="input-group-addon">
					<i class      ="fa fa-calendar bigger-110"></i>
				</span>
			</div>
		</div>					

</div>
			<br>	<br><br>

							<div align="center"><hr>
								<button class="btn btn-primary" onclick="send_consulta_hijo();send_registro_persona();" id="registrarHijo">
								<i class      ="ace-icon fa fa-floppy-o fa-lg"></i>
								Registrar
								</button>
							</div>
</form>		
</div>
	</div>
</div>	
<!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido -->
