
<div class="page-content ">
	<div class="page-header">
		<h1>
		Por favor seleccione a una persona para asignar un usuario.
		</h1>
	</div>
				
	<div class="row">
		<div class="col-xs-12">
			<div class="row">
				<div class="col-xs-12">
					<div class="table-header">
						Personas registradas.
					</div>
				<div>
						<form action="<?php  echo BASE_URL;?>personal/listing" method="post">
								<table id="dynamic-table" class="table table-striped table-bordered table-hover">
									<thead>
										<tr>
											<th class="center">
												<label class="pos-rel">
													#
												</label>
											</th>
											<th>Cedula</th>
											<th>Primer nombre</th>
											<th class="hidden-480">Segundo nombre</th>
											<th>Primer apellido</th>
											<th class="hidden-480">Segundo apellido</th>
											<th class="center">Acciones</th>
										</tr>
									</thead>

									<tbody>
									<?php foreach ($this->_listado as $persona): ?>
										<tr>
											<td class="center">
												<?php echo $persona['numeracion'];?>
											</td>

											<td>
												<?php echo $persona['cedula']; ?>
											</td>
											<td><?php echo $persona['nombre']; ?></td>
											<td class="hidden-480"><?php echo $persona['nombre2']; ?></td>
											<td><?php echo $persona['apellido']; ?></td>

											<td class="hidden-480">
												<?php echo $persona['apellido2']; ?>
											</td>

											<td class="center">
												<div class="hidden-sm hidden-xs action-buttons">
							<a class="btn-app  btn-primary  btn-sm">
								<label class="pos-rel">												
									<input type="radio" class="ace" value="<?php echo $persona['id_persona']; ?>" name="<?php echo 'check'.$cont ?>"/>
									<span class="lbl"></span>
								</label>
							</a>	
												</div>

											</td>
										</tr>
									<?php endforeach ?>
									</tbody>
								</table>
								<hr>

								</div><!-- /.col -->
							</form>

						</div>
					</div>
				</div>


						</div><!-- /.row -->

	<div align="center">
		<a class ="btn btn-danger" 
		onclick="closePickList()">
		<i class      ="fa fa-reply-all"></i>
		Salir
		</a>
	</div>						
					</div><!-- /.page-content -->

                    
					<div id="prod"></div>
                    <div id="resultado" align="center"></div>
                    <div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>
