<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
<div class="main-content-inner">
	<div class="widget-box divBlanco">
		<div class="alert alert-info" align="center">

			<h4>

				Personas Disponibles
				</h4>
		</div>
				
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
				
					<div id="consulta_personas" class="col-xs-12">
							<table id="consulta_personas_tabla"></table>
							<div id="jqGridPager"></div>
					</div>
				</div>
			</div>
		</div>	

<hr>
			<div align="center">
				<a class ="btn btn-success" 
				onclick="closePickList()">
				<i class      ="fa fa-reply-all"></i>
				Agregar
				</a>			
				<a class ="btn btn-danger" 
				onclick="closePickList()">
				<i class      ="fa fa-reply-all"></i>
				Salir
				</a>
			</div>	
			<br>					
	</div>
</div>
</div>

                    
					<div id="prod"></div>
                    <div id="resultado" align="center"></div>
                    <div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>
