<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
<div class="main-content-inner">
	<div class="widget-box divBlanco">
		<div class="alert alert-info" align="center">

			<h4>
				Usuarios Del Sistema.
				</h4>
		</div>
		<br>
			<div align="center" id="AgregarOtro" >
			<button class="btn btn-success" onclick="pickOpen('prod', 'id_prod', 
														'<?php echo BASE_URL."administracion/listarPersonal/" ?>',
														 90, 70, 90, 90);show('prod',500);show('id_aceptar',500);hide('id_buscar',500);">
			<i class      ="glyphicon glyphicon-plus"></i>
			Agregar usuario
			</button>
			</div>
			<br>					
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
							<div class="col-xs-12">
								<div class="table-header">
									Usuarios del sistema
								</div>
							</div>				
					<div id="consulta_personas" class="col-xs-12">
							<table id="consulta_personas_tabla"></table>
							<div id="jqGridPager"></div>
					</div>
				</div>
			</div>
		</div>			
<hr>
					
	</div>
</div>
</div>

                    
					<div id="prod"></div>
                    <div id="resultado" align="center"></div>
                    <div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>
