<div class="page-content ">
<div class="widget-box">
	<div class="alert alert-info" align="center">
		<h4>
		Consulta de correspondencias.
		</h4>
	</div>
	<br>
	<div align="center" id="AgregarOtro" >
		<button class="btn btn-primary" onclick="pickOpen('prod', 'id_prod',
		'<?php echo BASE_URL."correspondencia/registro" ?>',
		90, 53, 90, 90);show('prod',500);show('id_aceptar',500);hide('id_buscar',500);">
		<i class      ="glyphicon glyphicon-plus"></i>
		Registrar una correspondencia
		</button>
	</div>
	<br>
	<div class="row">
		<div class="col-xs-12">
			<div class="row">
				<div class="col-xs-12">
					<div class="table-header">
						Correspondencias registradas
					</div>
					<div>
						<form action="<?php  echo BASE_URL;?>personal/listing" method="post">
							<table id="dynamic-table" class="table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th>Nº</th>							
										<th>Oficina</th>
										<th>Asunto</th>
										<th>Instruccion</th>
										<th>Fecha</th>
										<th>tipo</th>
										<th class="center">Acciones</th>
									</tr>
								</thead>
								<tbody>
									<?php foreach ($this->_listado as $persona): ?>
									<tr>
										<td class="center">
											<?php echo $persona['numeracion'];?>
										</td>
										<td>
											<?php echo $persona['oficina']; ?>
										</td>
										<td><?php echo $persona['asunto']; ?></td>
										<td ><?php echo $persona['instruccion']; ?></td>
										<td><?php echo $persona['fecha']; ?></td>
										<td><?php echo $persona['tipo']; ?></td>
										<td class="center">
												<div class="hidden-sm hidden-xs action-buttons">
													<a class="btn-app  btn-detalles  btn-sm" id="detalle_persona"
														onclick="pickOpen('prod', 'id_prod',
														'<?php echo BASE_URL."personal/update/". $persona['id_persona'] ?>',
														90, 96, 85, 1);show('prod',500);show('id_aceptar',500);hide('id_buscar',500);"
														style=cursor:pointer; >
														<i class="glyphicon glyphicon-search"></i>
														Detalles
													</a>
													<a class="btn-app  btn-imprimir  btn-sm" id="detalle_persona" target="_blank"
														href="<?php echo BASE_URL."pdf/pdfDetallePersona/". $persona['id_persona'] ?>" >
														<i class="ace-icon fa fa-print bigger fa-lg"></i>
														Imprimir
													</a>
													<a class="btn-app btn-eliminar btn-sm" href="<?php echo BASE_URL."personal/delete/". $persona['id_persona'] ?>">
														<i class="ace-icon fa fa-trash-o bigger fa-lg"></i>
														Eliminar
													</a>
												</div>
										</td>
									</tr>
									<?php endforeach ?>
								</tbody>
							</table>
							<hr>
							</div><!-- /.col -->
						</form>
					</div>
				</div>
			</div>
			</div><!-- /.row -->
			</div><!-- /.page-content -->
			<div id="prod"></div>
			<div id="resultado" align="center"></div>
			<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>
</div>
