<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
	<div class="main-content-inner">
<div class="widget-box">
				<div class="alert alert-info" align="center">
					<h4>
					Consulta de correspondencias <i class="fa fa-envelope fa-lg"></i></h4>
					</h4>
				</div>
				<br>
				<div align="center" id="AgregarOtro" >
					<button class="btn btn-success" onclick="pickOpen('prod', 'id_prod',
					'<?php echo BASE_URL."correspondencia/registro" ?>',
					90, 60, 90, 60);show('prod',500);show('id_aceptar',500);hide('id_buscar',500);">
					<i class      ="glyphicon glyphicon-plus"></i>
					Registrar una correspondencia
					</button>
				</div>
				<br>
				<div class="row">
				<div class="col-xs-12">
						<div class="row">
							<div class="col-xs-12">
								<div class="table-header">
									Correspondencias registradas
								</div>
								<div>
										<div id="tabla_consulta" class="col-xs-12" align="center">
										<table id="consulta_correspondencia"></table>
										<div id="jqGridPager"></div>
										</div>
										
										</div><!-- /.col -->
								</div>
							</div>
							<hr><br>
						</div>
				</div>
</div>



	<div id="prod"></div>
			<div id="resultado" align="center"></div>
			<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>

	</div>
</div>	
<!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido -->			