            <div class="footer">
                <div class="footer-inner">
                    <div class="footer-content">
                        <span class="bigger-120">
                            <span class="blue bolder">MPPIC</span>
                            Ministerio Para El Poder Popular De Industria Y Comercio.
                        </span>

                    </div>
                </div>
            </div>
            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
                <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
            </a>
        </div><!-- /.main-container -->
     <!-- basic scripts -->
                    <?php  if (isset($_view_params['js']) && count($_view_params['js'])): ?>
        <?php   for ($i = 0; $i < count($_view_params['js']); $i++):  ?>
        <script src="<?php echo $_view_params['js'][$i]; ?>"></script>
        <?php   endfor; ?>
        <?php  endif;?>

        <script type="text/javascript">
            if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
        </script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/bootstrap.min.js"></script>

        <!-- page specific plugin scripts -->


        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery-ui.custom.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery.ui.touch-punch.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/chosen.jquery.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/fuelux.spinner.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/bootstrap-datepicker.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/bootstrap-timepicker.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/moment.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/daterangepicker.min.js"></script>
       
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/bootstrap-datetimepicker.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/bootstrap-colorpicker.min.js"></script>

                <!-- ace scripts -->
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/ace-elements.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/ace.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery.knob.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery.autosize.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery.maskedinput.min.js"></script>
        <script src="<?php echo PUBLIC_URL;?>plantilla/assets/js/bootstrap-tag.min.js"></script>


         <!-- scripts para alert personalizado  -->
        <script type="text/javascript" src="<?php echo PUBLIC_URL;?>js/wow-alert.js"></script>

    </body>
       
</html>
        <!-- inline scripts related to this page -->
        <script type="text/javascript">
            jQuery(function($) {
                $('.date-picker').datepicker({
                    autoclose: true,
                    todayHighlight: true
                }),
                $.mask.definitions['~']='[+-]';
                $('.input-mask-date').mask('99/99/9999');
                $('.input-mask-phone').mask('(999) 999-9999');
                $('.input-mask-eyescript').mask('~9.99 ~9.99 999');
                $(".input-mask-product").mask("a*-999-a999",{placeholder:" ",completed:function(){alert("You typed the following: "+this.val());}});
            });
        </script>