            <div class="footer">
                <div class="footer-inner">
                    <div class="footer-content">
                        <span class="bigger-120">
                            <span class="blue bolder">MPPIC</span>
                            Ministerio Para El Poder Popular De Industria Y Comercio.
                        </span>

                    </div>
                </div>
            </div>
        </div><!-- /.main-container -->

     <!-- basic scripts -->
        <script src="<?php echo PUBLIC_URL;?>/js/Librerias/ace-extra.js"></script> 
        <script src="<?php echo PUBLIC_URL;?>/js/Librerias/jquery.js"></script>
        <script src="<?php echo PUBLIC_URL;?>/js/Librerias/bootstrap.js"></script>
        <script type="text/javascript">
            if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo PUBLIC_URL;?>plantilla/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
        </script> 

        <!-- ace scripts -->
        <script src="<?php echo PUBLIC_URL;?>/js/Librerias/ace-elements.js"></script>
        <script src="<?php echo PUBLIC_URL;?>/js/Librerias/ace.min.js"></script>
         <!-- scripts para alert personalizado  -->
        <script type="text/javascript" src="<?php echo PUBLIC_URL;?>js/wow-alert.js"></script>
        <!-- Funcionalidades -->
        <script type="text/javascript" src="<?php echo PUBLIC_URL;?>js/ajax.js"></script>
                <?php  if (isset($_view_params['js']) && count($_view_params['js'])): ?>
        <?php   for ($i = 0; $i < count($_view_params['js']); $i++):  ?>
        <script src="<?php echo $_view_params['js'][$i]; ?>"></script>
        <?php   endfor; ?>
        <?php  endif;?>

    </body>
     
</html>


        <!-- inline scripts related to this page -->
        <!-- Calendario de Inputs -->
        <script type="text/javascript">
            jQuery(function($) {
                $('.date-picker').datepicker({
                       clearBtn: true,
                       autoclose: true,
                    language: "es",
                    daysOfWeekHighlighted: "0,1,2,3,4,5,6",
                    todayHighlight: true,
                });
                //or change it into a date range picker
                $('.input-daterange').datepicker({
                    clearBtn: true,
                    language: "es",
                    daysOfWeekHighlighted: "0,1,2,3,4,5,6",
                    autoclose: true,
                    todayHighlight: true,


                });

                  $(document).ready(function () { 
                    var selector = function (dateStr) {
                            var d1 = $('#desde').datepicker('getDate');
                            var d2 = $('#hasta').datepicker('getDate');
                            $('#desde').datepicker("option", "maxDate",d2); //new line           
                            $('#hasta').datepicker("option", "minDate",d1); // new line
                            var diff = 1;
                            if (d1 && d2) {
                                diff = diff + Math.floor((d2.getTime() - d1.getTime()) / 86400000);
                            }
                            $('#dias_habiles').val(diff);
                            //$('.minim').val(d1)
                        }    

                    $('#desde,#hasta').change(selector)
                    });

                $.mask.definitions['~']='[+-]';
                $('.input-mask-date').mask('99/99/9999');
                $('.input-mask-phone').mask('(9999) 999-9999');
                $('.input-mask-eyescript').mask('~9.99 ~9.99 999');
                $(".input-mask-product").mask("a*-999-a999",{placeholder:" ",completed:function(){alert("You typed the following: "+this.val());}});


           

                $('#gritter-center').on(ace.click_event, function(){
                    $.gritter.add({
                        title: 'This is a centered notification',
                        text: 'Just add a "gritter-center" class_name to your $.gritter.add or globally to $.gritter.options.class_name',
                        class_name: 'gritter-info gritter-center'
                    });
            
                    return false;
                });
        });

        </script>