<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
        <title>CATIC</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <!-- bootstrap & fontawesome -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/font-awesome/4.2.0/css/font-awesome.min.css" />
        <!-- alert personalizado -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/wow-alert.css" />
        <!-- ace styles -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/form.css" />
        <?php if(isset($_view_params['css'])&&count($_view_params['css'])): ?>
        <?php for($i=0;$i<count($_view_params['css']);$i++): ?>
        <link rel="stylesheet" href="<?php echo $_view_params['css'][$i]; ?>" type="text/css" />
        <?php endfor; ?>
        <?php endif;?>
    </head>
    <body class="no-skin" >
        <div id="navbar" class="navbar navbar-default">
            <img src="<?php echo PUBLIC_URL;?>img/cintillo.jpg" width="100%" height="100%">
            <div class="navbar-container" id="navbar-container">
                <div class="navbar-header pull-left" >
                    <a class="navbar-brand">
                       <h5 ><?php  echo APP_NAME; ?></h5>
                    </a>
                </div>
                <ul class="nav navbar-nav">
                    
                    <?php  if (isset($_view_params['menu'])):?>
                    <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>
                    <?php       if( $this-> _controller ==$_view_params['menu'][$i]['id']): ?>
                    <li class="active"><a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a></li>
                    <?php  else: ?>
                    <li><a href="<?php echo $_view_params['menu'][$i]['link'] ;?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a></li>
                    <?php  endif; ?>
                    <?php  endfor;?>
                    <?php  endif;?>
                    
                </ul>                
                <div class="navbar-buttons navbar-header pull-right" role="navigation">
                    <ul class="nav ace-nav">
                        
                        <!-- menu de login -->
                        <li class="light-blue">
                            <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                                
                                <span class="user-info">
                                    <small>Bienvenido,</small>
                                    <?php echo Session::get('user') ?>
                                </span>                                
                                <i class="ace-icon fa fa-caret-down"></i>
                            </a>
                            <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                                <li>
                                    <a href="#">
                                        <i class="ace-icon fa fa-cog"></i>
                                        Configuraciones.
                                    </a>
                                </li>
                                <li>
                                    <a href="profile.html">
                                        <i class="ace-icon fa fa-user"></i>
                                        Perfil.
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php  session_destroy(); echo BASE_URL;?>login/close">
                                        <i class="ace-icon fa fa-power-off"></i>
                                        Salir
                                    </a>
                                    
                                </li>
                            </ul>
                        </li>
                        <!-- fin menu de login -->
                    </ul>
                </div>
                </div><!-- /.navbar-container -->
            </div>
            
                
   