<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>CATIC</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <!-- bootstrap & fontawesome -->
        <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/css_menu/layout.css" />
            <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/css_menu/menu.css" />
            <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>js/script_menu.js" />
    <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/font-awesome/4.2.0/css/font-awesome.min.css" />
    <!-- alert personalizado -->
    <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/wow-alert.css" />
    <!-- ace styles -->
    
    <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>css/form.css" />
    <?php if(isset($_view_params['css'])&&count($_view_params['css'])): ?>
    <?php for($i=0;$i<count($_view_params['css']);$i++): ?>
    <link rel="stylesheet" href="<?php echo $_view_params['css'][$i]; ?>" type="text/css" />
    <?php endfor; ?>
    <?php endif;?>
    <link rel="stylesheet" href="<?php echo PUBLIC_URL;?>plantilla/assets/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />
</head>
<body class="no-skin" >
<!-- inicio_navbar --><!-- inicio_navbar --><!-- inicio_navbar --><!-- inicio_navbar --><!-- inicio_navbar --><!-- inicio_navbar --><!-- inicio_navbar --><!-- inicio_navbar -->
                    <div id="navbar" class="navbar navbar-default ">
                        <img src="<?php echo PUBLIC_URL;?>img/cintillo.jpg" width="100%" height="100%">
                            <div class="navbar-container " id="navbar-container">
                                        <div class="navbar-header pull-left" >
                                            <a class="navbar-brand">
                                                <h4 >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                                                <?php  echo APP_NAME; ?></h4>
                                            </a>
                                        </div>
                            </div><!-- /.navbar-container -->
                    </div><?php // echo '<pre>';print_r($_view_params['menu'][0]['submenu'][3]['submenuHijo']);echo '</pre>';die();    ?>

                                <ul id="nav">

                                    <?php  if (isset($_view_params['menu'])):?>
                                    <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>



                                    <li>
                                    <a href="<?php echo $_view_params['menu'][$i]['link'] ;?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>
                                    <?php  if ($_view_params['menu'][$i]['submenu']):?>
                                     <ul class="submenu">
                                    
                                    <?php  for ($j= 0; $j < count($_view_params['menu'][$i]['submenu']); $j++):?>

                                        <li> <a href="<?php echo  $_view_params['menu'][$i]['submenu'][$j]['link']; ?>"><?php echo $_view_params['menu'][$i]['submenu'][$j]['title'];?> 
                                        

                                        </li>               
                                    <?php  endfor;?>
                                         </ul> 
                                    <?php  endif;?> 

                                    </li>


                                    <?php  endfor;?>

                                    <?php  endif;?>                                        
    

                                </ul>

<!-- fin_navbar --><!-- fin_navbar --><!-- fin_navbar --><!-- fin_navbar --><!-- fin_navbar --><!-- fin_navbar --><!-- fin_navbar --><!-- fin_navbar -->