<!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido --><!-- contenido -->
<div class="main-content" >
	<div class="main-content-inner">
		<div class="widget-box" id="caja">
			<div class="alert alert-info" align="center">
				<h4>Consulta de vacaciones asignadas <i class="fa fa-users fa-lg"></i></h4>
			</div>
					<div class="row">
							<div class="col-xs-12">
								<div class="row">
									<div id="tabla_consulta" class="col-xs-12">
										<!-- PAGE CONTENT BEGINS -->
									<table id="jqGrid"></table>
									<div id="jqGridPager"></div>
									<!-- PAGE CONTENT ENDS -->
									</div><!-- /.col -->
								</div>
							</div>
					</div><!-- /.row -->
				<hr>
		</div>		
	</div>
</div>
<div id="dialog-confirm" title="Dialog Title" hidden="hidden">¿Esta seguro de Cancelar?</div>	
<div id="prod"></div>
<div id="resultado" align="center"></div>
<div  id='id_fondo_opaco' class="fondo_opaco" style="display:none"></div>

<!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido --><!-- fin_contenido -->
