	<div class="widget-box">
		<form action="<?php  echo BASE_URL;?>vacaciones/registro_vacaciones" method="post">
			<div class="alert alert-info" align="center">
				<h4>Asignacion de vacaciones <i class="fa fa-users fa-lg"></i></h4>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-12">
					<div class="col-sm-12" align="center" id="sandbox-container">
								<div class="col-sm-4">
									<label>Fecha de solicitud:</label>
									<div class="col-sm-7 input-group">
										<input  onkeypress="return letras(event)" autocomplete="off" class  ="input-sm form-control date-picker" name="fecha_solicitud" id="fecha_solicitud" type="date" data-date-format="yyyy-mm-dd"  />
										<span class   ="input-group-addon">
											<i class      ="fa 	fa-calendar  bigger-110"></i>
										</span>
									</div>
								</div>
								<div class="col-sm-4">
									<label>Fecha de inicio:</label>
									<div class="col-sm-7 input-group">
										<input autocomplete="off" type="text" class="input-sm form-control date-picker" name="desde" id="desde" placeholder="Desde"  data-date-format="yyyy-mm-dd"/>
										<span class   ="input-group-addon">
											<i class      ="fa 	fa-calendar  bigger-110"></i>
										</span>
									</div>
								</div>								
								<div class="col-sm-4" align="center">
								
									<label>Días hábiles correspondientes:</label>
									<div class="col-sm-4 input-group">
										<input autocomplete="off"  class  ="input-sm form-control" name="dias_habiles" id="dias_habiles" type="text"  />
										<span class   ="input-group-addon">
											<i class      ="fa 	fa-calculator bigger-110"></i>
										</span>
									</div>
									<br>
								</div>								


					</div>

					<div class="col-sm-12" align="center">
								<div class="col-sm-6">
									<label>Fecha final:</label>
									<div class="col-sm-5 input-group">
										<input  onkeypress="return letras(event)" autocomplete="off" class  ="input-sm form-control date-picker" name="hasta" id="hasta" type="date" data-date-format="yyyy-mm-dd" readonly="" />
										<span class   ="input-group-addon">
											<i class      ="fa 	fa-calendar  bigger-110"></i>
										</span>
									</div>
								</div>
								<div class="col-sm-6">
									<label>Fecha de reincorporacion:</label>
									<div class="col-sm-5 input-group">
										<input type="text" class="input-sm form-control date-picker" name="reincorporacion" id="reincorporacion" data-date-format="yyyy-mm-dd" readonly=""/>
										<span class   ="input-group-addon">
											<i class      ="fa 	fa-calendar  bigger-110"></i>
										</span>
									</div>
								</div>	
								<br><br><br>
					<hr>
					</div>

					
					<div class="" align="center">
						<div class="row">
							<div class="col-xs-12">
								<div class="table-header">
									Personas disponibles.
								</div>
								<div>
									<table id="dynamic-table" class="table table-striped table-bordered table-hover">
										<thead>
											<tr>
												<th class="center">
													<label class="pos-rel">
														#
													</label>
													<th class="center">Cedula</th>
													<th class="center">Nombres</th>
													<th class="center">Apellidos</th>
													<th class="center">Fecha de ingreso</th>
													<th class="center">Teléfono</th>
													<th class="center">Seleccione</th>
												</tr>
											</thead>
											<tbody>
												<?php $cont=0; foreach ($this->_listado as $persona): $cont++;?>
												<tr>
													<td class="center"><?php echo $persona['numeracion'];?></td>
													<td><?php echo $persona['cedula']; ?></td>
													<td><?php echo $persona['nombre']; ?>&nbsp;&nbsp;<?php echo $persona['nombre2']; ?></td>
													<td><?php echo $persona['apellido']; ?>&nbsp;&nbsp;<?php echo $persona['apellido2']; ?></td>
													<td class="center"><?php echo $persona['fecha_ingreso'];?></td>
													<td class="center"><?php echo $persona['telefono'];?></td>
													<th class="center">
														<a class="btn-app  btn-primary  btn-sm">
															<label class="pos-rel">
																<input type="checkbox" class="ace" value="<?php echo $persona['id_persona']; ?>" name="<?php echo 'check'.$cont ?>"/>
																<span class="lbl"></span>
															</label>
														</a>
														<input type="hidden" value="<?php echo $cont?>" name="contador" id="contador">
													</th>
												</tr>
												<?php endforeach ?>
											</tbody>
										</table>
										</div><!-- /.col -->
									</div>
								</div>
							</div>
							<br>
							<div align="center">
								<button class="btn btn-primary" type="submit" align="center">
								<i class="ace-icon fa fa-floppy-o fa-lg"></i>
								Registrar vacaciones
								</button>
							</div>
						</form>
						<br>
					</div>
				</div>
			</div>
